### ISSUE TITLE
I think home & menu should be  pages not posts will be better!

### ISSUE THREAD

**Issue by codiy1992** [kaiiiz/hexo-theme-book#16]
1. home & menu under /source/_posts/ will not work with other themes
2. home & menu should be a page not a post

**Comment by kaiiiz** [comment]
Thanks for your suggestion! I think you are right. I'll modify the render script from rendering post to page in the next MAJOR version release. (3.x.x)

**Comment by kaiiiz** [comment]
This feature is implemented in v3.0.0.
