### ISSUE TITLE
MarkDown page can't be rendered

### ISSUE THREAD

**Issue by Undo101** [kaiiiz/hexo-theme-book#21]
The point is that it succeeded, I don't know what the problem is, I need help, please.
there are some configs in my project:
![image](https://user-images.githubusercontent.com/26062774/82551971-d5577d80-9b93-11ea-8fc2-31d5908754ce.png)
![image](https://user-images.githubusercontent.com/26062774/82552042-f61fd300-9b93-11ea-93b4-93c9019c9f13.png)
![image](https://user-images.githubusercontent.com/26062774/82552120-16e82880-9b94-11ea-8fec-1d7b786c8db3.png)

**Comment by kaiiiz** [comment]
It's seems that the home_page is not render successfully in your local server. But I visited your project in https://github.com/Undo101/Undo101.github.io, the home page is render successfully, so I'm not sure what problem you met. Maybe try `hexo clean` and `hexo g` before you run `hexo s`?

P.S Please remind that home_page and menu_page need to place under source/_posts.
