### ISSUE TITLE
cannot find the markdown file

### ISSUE THREAD

**Issue by xuyuluo** [kaiiiz/hexo-theme-book#26]
I wanted to put new items into the menu, but when I clicked the book, it showed cannot find /deep-learning/first-post. have no idea where to fix this.

**Comment by kaiiiz** [comment]
This theme treats the menu just like regular posts, so the issue is that your site doesn't have the route `/deep-learning/first-post`. Check whether you have set base url in your config or not, or maybe you has typo in your post name.

**Comment by xuyuluo** [comment]
I can see the menu I edited, but links inside the menu cannot be found. the route should be correct.

**Comment by kaiiiz** [comment]
Can you try to put this link to an ordinary post and check whether this link work or not?

The other blog may work because they automatically create these links in the render process, but this theme is fully configurable in this part.

**Comment by xuyuluo** [comment]
No, it doesn't work.

**Comment by kaiiiz** [comment]
So this is the issue that hexo doesn't create route for `/deep-learning/first-post` as I mention before. Check whether you have `deep-learning` folder under `source/_posts` folder, and `first-post.md` file under `deep-learning` folder.

**Comment by xuyuluo** [comment]
This is my folder tree. 
├── home.md
├── menu.md
└── _posts
    ├── deep-learning
    │   ├── papers-to-read.md
    │   ├── read-caffe.md
    │   └── self-att.md
    ├── first.md
    ├── language-learning
    │   ├── eng-learning.md
    │   ├── ger-learning.md
    │   └── word-to-replace-do.md
    ├── programming
    │   ├── keyword-yield.md
    │   ├── py-c-etxtension.md
    │   └── pythonic-codes.md
    ├── reading
    │   └── book-recom.md
    ├── tips-tricks
    │   ├── git-usage.md
    │   ├── handle-strings.md
    │   └── some-tricks.md

**Comment by kaiiiz** [comment]
You don't have `first-post.md` under `deep-learning` folder, so this is the expected behavior, hexo will not generate route for `/deep-learning/first-post`.

**Comment by xuyuluo** [comment]
cannot find /deep-learning/first-post now
├── about
│   ├── index.md
│   └── morning.jpg
├── gallery
│   └── thumbnail
│       ├── ita.jpg
│       ├── me.jpg
│       ├── morning.jpg
│       └── spaghetti.jpg
├── home.md
├── menu.md
└── _posts
    ├── deep-learning
    │   ├── first-post.md
    │   ├── papers-to-read.md
    │   ├── read-caffe.md
    │   └── self-att.md
    ├── language-learning
    │   ├── eng-learning.md
    │   ├── ger-learning.md
    │   └── word-to-replace-do.md
    ├── programming
    │   ├── keyword-yield.md
    │   ├── py-c-etxtension.md
    │   └── pythonic-codes.md
    ├── reading
    │   └── book-recom.md
    ├── tips-tricks
    │   ├── git-usage.md
    │   ├── handle-strings.md
    │   └── some-tricks.md
    └── writing
        └── my-research.md

**Comment by kaiiiz** [comment]
Try `hexo clean` and `hexo generate` again, check whether the static page is generated.

**Comment by xuyuluo** [comment]
I used another theme before. Is this might be reason? And I also noticed the difference of the homepage. Yours is highlighted. Mine is not

Yours
![Screenshot from 2020-11-04 13-54-41](https://user-images.githubusercontent.com/24487078/98114427-8aad9180-1ea5-11eb-80ea-523b99401e48.png)
Mine
![Screenshot from 2020-11-04 13-54-19](https://user-images.githubusercontent.com/24487078/98114447-913c0900-1ea5-11eb-9835-8779c5103ca9.png)

**Comment by kaiiiz** [comment]
No, this is expected behavior. If you already has file, hexo will generate that route, so check again whether it work or not.

However, the routing issue is not relative with this theme, it is defined by the framework, this theme only render the corresponding markdown file to the right position and it's your responsibility to write the correct markdown file. Please go checking hexo doc in details, you might find more information in the documents.

I visit to your website `xuyuluo.github.io`, and your home link is `/first` which is not the base url (`/`). The menu entry will only be highlighted if you are currently under that path.

**Comment by xuyuluo** [comment]
Okay. Thanks. I will look into it. I tested this with localhost.
