### ISSUE TITLE
abbr format for months & Chinese translation support please

### ISSUE THREAD

**Issue by forliuyifei** [kaiiiz/hexo-theme-book#28]
It is recommended to use English abbreviations for the months.  
 **November** is too long  
**Nov.** is more appropriate

![image](https://user-images.githubusercontent.com/53306807/98534040-d81f6980-22be-11eb-9329-2a524f3249a1.png)

**Comment by kaiiiz** [comment]
The format of the date in post meta is following the setting in site's `_config.yml`. There has a option call `date_format`, you can checkout [the document](https://hexo.io/docs/configuration.html#Date-Time-format) for more information.
