### ISSUE TITLE
it seems `.table-wrapper` is not effective

### ISSUE THREAD

**Issue by xieyuheng** [kaiiiz/hexo-theme-book#4]
changing `$border-color` does not effect table :: https://github.com/kaiiiz/hexo-theme-book/blob/master/source/css/book.scss#L147

**Comment by xieyuheng** [comment]
the difference is "in list" vs "not in list"
![](https://img.vim-cn.com/7b/2eb8b3cf46681fc4b4a10295f4dd3a3a0dd03e.png)

**Comment by xieyuheng** [comment]
I suggest
1. making **[NOT IN LIST]** the same size as **[IN LIST]**.
2. and add borders to both of them.

I do not have enough knowledge of scss to implement this.
I wish you can help.

**Comment by xieyuheng** [comment]
border at all sides

**Comment by xieyuheng** [comment]
I am using your theme extensively now.

I will learn more about scss and try to fix this.

**Comment by kaiiiz** [comment]
@xieyuheng thanks for inform this issue. I have already fixed that in [5692c4](https://github.com/kaiiiz/hexo-theme-book/commit/5692c470a90a2d16c05dbb6ace0d611d2fafd51d).

Now it may look like your expect.

![image](https://user-images.githubusercontent.com/30596812/67875662-a1722780-fb71-11e9-8ffc-968f726c372b.png)

See [demo](https://kaiiiz.github.io/hexo-theme-book-demo/test/list-test/) for more detail.

**Comment by kaiiiz** [comment]
@xieyuheng I found that code block is also in \<table\> tag. It may cause unnecessary margin.  So I modify selector to `'.book-post > table, li > table'`

**Comment by xieyuheng** [comment]
thanks for leting me know.
