### ISSUE TITLE
The style is different from the author's example.

### ISSUE THREAD

**Issue by lingerois** [kaiiiz/hexo-theme-book#6]
Are there any configuration items could change the style?

![image](https://user-images.githubusercontent.com/9911953/69823459-e27a5c00-1243-11ea-94a7-def742bdfac0.png)

**Comment by lingerois** [comment]
Sorry I for misposting issue of other repos here. I corrected it and changed it to a issue of this repo.

**Comment by xieyuheng** [comment]
@lingerois I think your picture looks different because you opened the generated html files directly in a web browser, instead of run `hexo server` and visit http://localhost:4000.

**Comment by lingerois** [comment]
It was caused by the differences between renderer, which I though wasn't a problem. Thanks.

**Comment by xieyuheng** [comment]
> differences between renderer

what  differences between renderer?

**Comment by lingerois** [comment]
I've got it. I though scss is an renderer, so I didn't install it. It all works well after installed it.
